services:
  - type: web
    name: portfolio-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: jagdishwork04@gmail.com
      - key: EMAIL_TO
        value: js8724285@gmail.com

  - type: web
    name: portfolio-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://portfolio-backend.onrender.com
